### ISSUE TITLE
Area is justified at the top left intead of center

### ISSUE THREAD

**Issue by Doksha** [Kuuuube/Tablet_Area_Randomizer#1]
I'll preface this by saying I do not know anything about coding in c#, so I am somewhat guessing based on my knowledge of python (and basic math), but it should work as long as you can get the width and height of the tablet
currently the location of the cursor is only multiplied by the random area, which naturally justifies at the top left corner (input.X *= rand_expanded, input.Y *= rand_expanded) 
to fix this you could expand the equation to input.X = rand_expanded * (input.X / \<tablet width\>)+(\<tablet width\> - input.X)/2), rand_expanded = input.Y * (input.X / \<tablet height\>)+(\<tablet height\> - input.Y)/2)

**Comment by Kuuuube** [comment]
Late response but this is actually the intended way for input to be handled. It seems so have gotten broken at some point. I have fixed this by reverting back to the old centering method. The release will be available when OTD 0.6.0 is released.

Thank you for the bug report.
